export interface VideoItem {
  thumbnail: string;
  duration: string;
  title: string;
  author_name: string;
  link: string;
}

// Auto-generated by scripts/fetch-youtube-videos.mjs — do not edit by hand.
// Source: https://www.youtube.com/@BABOKEFILMS/videos
export const videos: VideoItem[] = [
  {
    thumbnail: "https://i.ytimg.com/vi/fFIaqmh-HmI/hqdefault.jpg",
    duration: "12:44",
    title: "Le Baba du Tsapiky raconte son histoire.",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=fFIaqmh-HmI",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/s7_VhKDCHcE/hqdefault.jpg",
    duration: "30:39",
    title: "FITAMPOHA 2026- Saint-Augustin, Anantsono ,Toliara.",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=s7_VhKDCHcE",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/vupxm9kZQo8/hqdefault.jpg",
    duration: "1:45",
    title: "LUMIX GH5 IN 2024 - a WORKOUT VIDEO - RABAT ,MOROCCO (LUMIX 25mm F1.7)",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=vupxm9kZQo8",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/XVNXEC-m9eg/hqdefault.jpg",
    duration: "1:16",
    title: "Motivation | A Cinematic Short Film (LUMIX GH5)",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=XVNXEC-m9eg",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/n_z-YCsdXvQ/hqdefault.jpg",
    duration: "2:13",
    title: "\"The patriotism\" | A Cinematic Short Film",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=n_z-YCsdXvQ",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/8liwN5rUXPo/hqdefault.jpg",
    duration: "0:22",
    title: "Watersky Studio",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=8liwN5rUXPo",
  },
];
