export interface VideoItem {
  thumbnail: string;
  duration: string;
  title: string;
  author_name: string;
  link: string;
}

// Auto-generated by scripts/fetch-youtube-videos.mjs — do not edit by hand.
// Source: https://www.youtube.com/@BABOKEFILMS/videos
export const videos: VideoItem[] = [
  {
    thumbnail: "https://i.ytimg.com/vi/SbhFS_CXUN8/hqdefault.jpg",
    duration: "3:42",
    title: "FMM BETANIA - MAHAVELO GNY RAHA ATAONY",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=SbhFS_CXUN8",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/fMVZ_OdPazQ/hqdefault.jpg",
    duration: "4:02",
    title: "VAIN'AF -JOKE MAMY (Nouveauté gasy 2025)",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=fMVZ_OdPazQ",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/zMSYPuBxlHw/hqdefault.jpg",
    duration: "3:52",
    title: "VAIN'AF - VAIN'AF (Nouveauté clip gasy 2026)",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=zMSYPuBxlHw",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/jMEF9rgG1iQ/hqdefault.jpg",
    duration: "3:30",
    title: "601 BRO - TSY HO ZAO ( LYRICS AVRIL 2025 )",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=jMEF9rgG1iQ",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/aF_XP1Ey_G4/hqdefault.jpg",
    duration: "2:46",
    title: "601 Bro - Engao tseky (Official Lyric Video)",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=aF_XP1Ey_G4",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/ULClERieOwg/hqdefault.jpg",
    duration: "2:20",
    title: "SOUDARÀ - REAL GASY MAN ( Slaan freestyle part 2)",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=ULClERieOwg",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/xHpiadtegQw/hqdefault.jpg",
    duration: "4:44",
    title: "SOUDARÀ Feat DM - ꞮA SHA ?(Prod by Masoandro Capital)",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=xHpiadtegQw",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/2PRCkgpSIJQ/hqdefault.jpg",
    duration: "4:07",
    title: "🔥601 BRO - Femme de ma vie (Nouveau Clip Officiel 4K)",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=2PRCkgpSIJQ",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/gE-0sHt1kDE/hqdefault.jpg",
    duration: "3:35",
    title: "SOA AVAO - 601 BRO(Prod by Masoandro Capital ) 2024",
    author_name: "Directed by Tony Braven",
    link: "https://www.youtube.com/watch?v=gE-0sHt1kDE",
  },
];
